// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBebc3V720InPHZYZ5AhaYhUil1CtoA2ic',
    appId: '1:110517099884:web:2a9c1e4e1cb9c9e39ee749',
    messagingSenderId: '110517099884',
    projectId: 'planify-712d4',
    authDomain: 'planify-712d4.firebaseapp.com',
    storageBucket: 'planify-712d4.firebasestorage.app',
    measurementId: 'G-7LPMCJN5LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAis2sfflD-m_iCFKZuP4Xf5bx1PUFpwcs',
    appId: '1:110517099884:android:073c158a06bfb5f59ee749',
    messagingSenderId: '110517099884',
    projectId: 'planify-712d4',
    storageBucket: 'planify-712d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZiQGPrbAdmK-l0tE59DU-uHcMulQzFjA',
    appId: '1:110517099884:ios:af47ecd100adf2699ee749',
    messagingSenderId: '110517099884',
    projectId: 'planify-712d4',
    storageBucket: 'planify-712d4.firebasestorage.app',
    iosClientId: '110517099884-fstb624bl1r6b5ruupng5rpsn2peppo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.planify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZiQGPrbAdmK-l0tE59DU-uHcMulQzFjA',
    appId: '1:110517099884:ios:af47ecd100adf2699ee749',
    messagingSenderId: '110517099884',
    projectId: 'planify-712d4',
    storageBucket: 'planify-712d4.firebasestorage.app',
    iosClientId: '110517099884-fstb624bl1r6b5ruupng5rpsn2peppo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.planify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBebc3V720InPHZYZ5AhaYhUil1CtoA2ic',
    appId: '1:110517099884:web:7ea2c71f8aef1b7d9ee749',
    messagingSenderId: '110517099884',
    projectId: 'planify-712d4',
    authDomain: 'planify-712d4.firebaseapp.com',
    storageBucket: 'planify-712d4.firebasestorage.app',
    measurementId: 'G-C24V5ZZKEL',
  );
}
